# Generated by Django 4.0.4 on 2022-05-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_post_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='nome',
            field=models.CharField(max_length=30),
        ),
    ]
