# Generated by Django 4.0.4 on 2022-06-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_cadeira_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='TFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('autores', models.TextField(default='Authors')),
                ('orientadores', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('resumo', models.TextField(default='Text')),
                ('relatorio', models.DateTimeField(auto_now_add=True)),
                ('git', models.URLField()),
                ('video', models.URLField()),
            ],
        ),
    ]
