# Generated by Django 4.0.5 on 2022-06-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_tfc'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfc',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
